name: Validate PullRequest

on: pull_request

jobs:
  BuildWheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-10.15 ]
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - run: make set-version
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.0.0a4
        env:
          CIBW_ARCHS: native
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install twine==3.4.*
      - name: Publish wheels to test pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        run: twine upload wheelhouse/*

  BuildSdist:
    name: Build sdist
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - run: make set-version
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python setup.py sdist
      - run: pip install twine==3.4.*
      - name: Publish package to test pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        run: twine upload dist/*
